version: '3'
services:

  db:
    image: mongo:3.2.16
    expose:
      - "27017"
      - "37017"
    command: --smallfiles

  server:
    build: ./server
    env_file:
      - ./server/environment-dev.env
    ports:
      - "3030:3030"
    volumes:
      - ./server:/var/www/:rw
      - /var/www/node_modules
    links:
      - db:db
    command: npm start

  client:
    build: ./client
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
    volumes:
      - ./client:/var/www/:rw
      - /var/www/node_modules
    command: npm run dev
